# Generated by Django 4.2.18 on 2025-02-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
