# Generated by Django 4.2.18 on 2025-04-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_reservation_email_alter_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
