# Generated by Django 4.2.18 on 2025-05-03 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_reservation_date_alter_reservation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
    ]
