# Generated by Django 4.2.18 on 2025-05-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_reservation_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('name', 'date', 'time')},
        ),
    ]
